[from-internal]
exten => 100,1,Answer()
 same => n,Echo()
 same => n,Hangup()

exten => _9XXX,1,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

exten => _X.,1,Hangup()

[from-external]
exten => _X.,1,Hangup()
