[global]
rtp_symmetric=yes

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=172.16.0.0/12
local_net=10.0.0.0/8
external_media_address=38.242.147.192
bind_rtp_to_media_address=no
external_signaling_address=38.242.147.192
media_address=38.242.147.192
bind_rtp_to_media_address=no

[100]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
allow=alaw
auth=100-auth
aors=100
direct_media=no
rewrite_contact=yes
force_rport=yes
rtp_symmetric=yes

media_address=38.242.147.192
bind_rtp_to_media_address=no
[100-auth]
type=auth
auth_type=userpass
password=test123
username=100

[100]
type=aor
max_contacts=5
remove_existing=yes

[9000]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
allow=alaw
auth=9000-auth
aors=9000
direct_media=no
rewrite_contact=yes
force_rport=yes
rtp_symmetric=yes

media_address=38.242.147.192
bind_rtp_to_media_address=no
[9000-auth]
type=auth
auth_type=userpass
password=dograh9000
username=9000

[9000]
type=aor
max_contacts=5
remove_existing=yes

[9001]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
allow=alaw
auth=9001-auth
aors=9001
direct_media=no
rewrite_contact=yes
force_rport=yes
rtp_symmetric=yes

media_address=38.242.147.192
bind_rtp_to_media_address=no
[9001-auth]
type=auth
auth_type=userpass
password=dograh9001
username=9001

[9001]
type=aor
max_contacts=5
remove_existing=yes
