[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[9000]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
allow=alaw
auth=9000-auth
aors=9000

[9000-auth]
type=auth
auth_type=userpass
password=dograh9000
username=9000

[9000]
type=aor
max_contacts=1

[9001]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
allow=alaw
auth=9001-auth
aors=9001

[9001-auth]
type=auth
auth_type=userpass
password=dograh9001
username=9001

[9001]
type=aor
max_contacts=1
